# ------------------------------------------------------------------------------
# Demonstrate how to define and use context information
#
# Reference
#
# - Context: https://docs.github.com/en/actions/learn-github-actions/contexts
# ------------------------------------------------------------------------------
name: 01_05_context_information
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: show context
        run: |
          echo github.workflow_ref = ${{ github.workflow_ref }}
