# demonstrate how to orchestrate jobs
name: 01_03_orchestrate_jobs
on:
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
#
# - Defining prerequisite jobs: https://docs.github.com/en/actions/using-jobs/using-jobs-in-a-workflow#defining-prerequisite-jobs
# - jobs.<job_id>.needs: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idneeds
jobs:
  # the DAG diagram looks like:
  # build -> [test1, test2] -> deploy
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: echo building
  test1:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: test1
        run: echo testing
  test2:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: test2
        run: echo testing
  deploy:
    needs: [test1, test2]
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo deploying
