# This is a basic workflow to help you get started with Actions

name: cache_python_package_dependencies

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  without_cache:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3 # https://github.com/marketplace/actions/checkout
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      # Runs a single command using the runners shell
      - name: install python dependencies
        run: pip install -r examples/cache_python_package_dependencies/requirements.txt
  with_cache:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3 # https://github.com/marketplace/actions/checkout
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      # Runs a single command using the runners shell
      - name: install python dependencies
        run: pip install -r examples/cache_python_package_dependencies/requirements.txt
