# This is a basic workflow to help you get started with Actions

name: github_action_ui_demo

on:
  workflow_dispatch:

jobs:
  # Using jobs in a workflow: https://docs.github.com/en/actions/using-jobs/using-jobs-in-a-workflow
  job_1:
    name: Job 1
    runs-on: ubuntu-latest
    steps:
      - name: Job 1, step 1
        run: echo "This is job 1, step 1"
      - name: Job 1, step 2
        run: echo "This is job 1, step 2"
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: show colorful console output
        run: |
          pip install rich
          python examples/github_action_ui/show_rich_color.py
  job_2:
    name: Job 2
    needs: job_1
    runs-on: ubuntu-latest
    steps:
      - name: Job 2, step 1
        run: echo "This is job 2, step 1"
      - name: Job 2, step 2
        run: echo "This is job 2, step 2"
  job_3:
    name: Job 3
    needs: job_1
    runs-on: ubuntu-latest
    steps:
      - name: Job 3, step 1
        run: echo "This is job 3, step 1"
      - name: Job 3, step 2
        run: echo "This is job 3, step 2"
  job_4:
    name: Job 4
    needs: [job_2, job_3]
    runs-on: ubuntu-latest
    steps:
      - name: Job 4, step 1
        run: echo "This is job 4, step 1"
      - name: Job 4, step 2
        run: echo "This is job 4, step 2"
