# This is a minimal viable GitHub Action Workflow
name: s001_minimal_workflow
# Controls when the action will run.
# Reference:
# - on: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on
# - Events that trigger workflows: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on:
  # To enable a workflow to be triggered manually, you need to configure the workflow_dispatch event.
  # - workflow_dispatch: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
  # - Manually running a workflow: https://docs.github.com/en/actions/using-workflows/manually-running-a-workflow
  # Allows you to run this workflow manually from the GitHub Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3 # https://github.com/marketplace/actions/checkout
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo build your project
          echo test your project
          echo deploy your project
