# This is a minimal viable GitHub Action Workflow
name: s005_workflow_dispatch_inputs
on:
  workflow_dispatch:
    inputs:
      env_name:
        description: environment name, for example, dev, test, prod
        options:
          - dev
          - test
          - prod
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Display the current environment
        run: |
          echo "env_name: ${{ github.event.inputs.env_name }}"
